# Generated by Django 4.2.4 on 2023-09-20 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_address_order_alter_productinfo_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.address",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="order",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="cart",
            field=models.ForeignKey(
                default=12,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="order_item",
                to="products.cart",
            ),
        ),
    ]
