# Generated by Django 4.2.4 on 2023-09-21 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_order_complete_alter_order_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productinfo",
            name="address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.address",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.address",
            ),
        ),
    ]
