# Generated by Django 4.2.4 on 2023-09-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_productinfo_address_alter_order_address"),
    ]

    operations = [
        migrations.RemoveField(model_name="address", name="zipcode",),
        migrations.AddField(
            model_name="address",
            name="area",
            field=models.CharField(default="not set", max_length=100),
        ),
        migrations.AddField(
            model_name="address", name="area_id", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="address", name="city_id", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="address",
            name="country",
            field=models.CharField(default="not set", max_length=100),
        ),
        migrations.AddField(
            model_name="address",
            name="country_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="address",
            name="latitude",
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name="address",
            name="longlitude",
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name="address", name="state_id", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="address",
            name="suburb",
            field=models.CharField(default="not set", max_length=100),
        ),
        migrations.AddField(
            model_name="address",
            name="suburb_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productinfo",
            name="height",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productinfo",
            name="length",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productinfo",
            name="weight",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productinfo",
            name="width",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(default="not set", max_length=100),
        ),
        migrations.AlterField(
            model_name="address", name="state", field=models.CharField(max_length=100),
        ),
    ]
