# Generated by Django 4.2.4 on 2023-10-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_address_address_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productinfo", name="height", field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="productinfo", name="length", field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="productinfo", name="weight", field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="productinfo", name="width", field=models.FloatField(default=0),
        ),
    ]
