# Generated by Django 4.2.4 on 2023-10-03 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_alter_productinfo_height_alter_productinfo_length_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productpicture",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mypicture",
                to="products.productinfo",
            ),
        ),
    ]
