# Generated by Django 4.2.4 on 2023-10-05 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_alter_productinfo_address"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="complete",),
        migrations.AddField(
            model_name="order",
            name="product_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("0", "Hasn't Paid"),
                    ("1", "Payment Verified"),
                    ("2", "Processing"),
                    ("3", "Delivering"),
                    ("4", "Arrived"),
                    ("5", "Complete"),
                    ("6", "Complained"),
                ],
                default="0",
                max_length=2,
            ),
        ),
    ]
