# Generated by Django 4.2.4 on 2023-10-05 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0015_remove_orderitem_cart_remove_orderitem_order_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=200, unique=True),
                ),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                (
                    "product_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("weight", models.FloatField()),
                ("length", models.FloatField()),
                ("width", models.FloatField()),
                ("height", models.FloatField()),
                ("rate_id", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("0", "Hasn't Paid"),
                            ("1", "Payment Verified"),
                            ("2", "Processing"),
                            ("3", "Delivering"),
                            ("4", "Arrived"),
                            ("5", "Complete"),
                            ("6", "Complained"),
                        ],
                        default="0",
                        max_length=2,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_customer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="destination",
                        to="products.address",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="origin",
                        to="products.address",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_seller",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_add", models.DateTimeField(auto_now_add=True)),
                (
                    "cart",
                    models.ForeignKey(
                        default=12,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="order_item",
                        to="products.cart",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_item",
                        to="products.order",
                    ),
                ),
            ],
        ),
    ]
