# Generated by Django 4.2.4 on 2023-10-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0017_alter_order_product_cost_alter_order_shipping_cost_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_id_shipper",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("0", "Hasn't Paid"),
                    ("1", "Payment Verified"),
                    ("2", "Processing"),
                    ("3", "Delivering"),
                    ("4", "Complete"),
                    ("5", "Complained"),
                ],
                default="0",
                max_length=2,
            ),
        ),
    ]
