from django.urls import path
from .views import *

urlpatterns = [
    path("list/", ProductListView.as_view()),
    path("mylist/", MyProductListView.as_view()),
    path("mylist/action/<int:pk>/", ProductEditDeleteView.as_view()),
    path("picture/<int:product>/", ProductPictureAddView.as_view()),
    path("picture/action/<int:pk>/", ProductPictureEditDelete.as_view()),
    path("list/category/<str:slug>/", ProductListFilterView.as_view()),
    path("list/search/", ProductListSearchView.as_view()),
    path("detail/<str:slug>/", ProductDetailView.as_view()),
    path("category/", CategoryProductView.as_view()),
    path("cart/<int:pk>/", CartView.as_view()),
    path("add/cart/", AddCartView.as_view()),
    path("cart/action/<int:pk>/", UpdateDeleteCartView.as_view()),
    path("cart/action/multiple-delete/", MultipleDeleteView.as_view()),
    path("cart/action/set-bought/", ChangeCartToBoughtView.as_view()),
    # path("checkout/<int:pk>/", CheckoutView.as_view()),
    path("shipping/address/", AddressListView.as_view()),
    path("shipping/address/action/<int:pk>/", AddressDetailView.as_view()),
    path("order-item/multiple/backend-process/", OrderShippingBackendProcess.as_view()),
    path("order-item/multiple/", MultipleOrderItemView.as_view()),
    path("order/add-shipper-id/", AddOrderIdShipperView.as_view()),
    path("order/list/", OrderListView.as_view()),
    path("order/list/customer/", OrderListCustomerSideView.as_view()),
    path("order/list/customer/count/", OrderUncompleteCountView.as_view()),
    path("order/list/seller/", OrderListSellerSideView.as_view()),
    path("order/list/complained/admin/", OrderComplainedAdminView.as_view()),
    path("order/payment-verified/", OrderChangePaymentVerified.as_view()),
    path("order/processing/", OrderChangeProcessing.as_view()),
    path("order/delivering/", OrderChangeDelivering.as_view()),
    path("order/complete/", OrderChangeComplete.as_view()),
    path("order/complained/", OrderChangeComplained.as_view()),
    path("address/country/", GetCountryFromShipper.as_view()),
    path("address/state/<int:country>/", GetStateFromShipper.as_view()),
    path("address/city/<int:state>/", GetCityFromShipper.as_view()),
    path("address/suburb/<int:city>/", GetSuburbFromShipper.as_view()),
    path("address/area/<int:suburb>/", GetAreaFromShipper.as_view()),
    path("price-check/", PriceCheckView.as_view()),
    path("checkout/address/", CheckOutByAddressView.as_view()),
    path("order/shipping/", OrderShippingView.as_view()),
    path("pickup/shipping/", RequestPickUpView.as_view()),
    path("check/shipping/<str:shipper_id>/", CheckResiShipperView.as_view()),
    path("complain/add/", AddComplainView.as_view()),
    path("complain/list/<int:order>/", ComplainListView.as_view()),
    path("complain/delete/<int:pk>/", DeleteComplainView.as_view()),
    path("order/cancel/<str:transaction_id>/", DeleteOrderView.as_view()),
    path("payment/", PaymentMidtransView.as_view()),
]